config/routes.rb
Adapt::Application.routes.draw do
  devise_for :users, :controllers => { :sessions => "sessions" } do
    get "login",  :to => "sessions#new"
    get "logout", :to => "sessions#destroy"
  end

  devise_scope :user do
    resources :sessions
  end

  namespace :adapt do
    resources :studies do
      member do
        post 'approve'
        post 'manage'
        post 'submit'
      end
    end

    resources :attachments do
      get 'download', :on => :member
    end

    resources :licences do
      post 'accept', :on => :member
    end

    resources :dois do
      post 'transmit', :on => :member
    end
  end

  root :to => 'adapt/studies#index'
end

app/models/adapt/doi.rb
class Adapt::Doi < ActiveRecord::Base
  set_table_name 'adapt_dois'

  validates_presence_of :title, :message => 'May not be blank.'
  validates_presence_of :creators, :message => 'At least one name must be given.'
  validates_presence_of :publisher, :message => 'May not be blank.'
  validates_presence_of :year

  def data_cite
    av = ActionView::Base.new(*Rails.configuration.paths["app/views"])
    av.assign :doi => self
    av.render 'adapt/dois/datacite.xml'
  end
end

app/models/adapt/generic.rb
class Adapt::Generic
  def initialize(data)
    data = { :value => data } if data.is_a? String
    class << self; self; end.class_eval { attr_accessor *data.keys }
    data.each { |key, val| instance_variable_set(:"@#{key}", val) }
  end

  def persisted?
    false
  end
end

app/models/adapt/model_support.rb
module Adapt::ModelSupport
  def parse_and_validate_date(attribute, value, min_year = 1000, max_year = 2999)
    result = false
    begin
      begin
        date = Adapt::PartialDate.new(value)
      rescue
        date = Adapt::PartialDate.new(Date.parse(value))
      end
    rescue => ex
      errors.add attribute, "#{ex.message.capitalize}: '#{value}'."
    else
      if not (min_year..max_year).include? date.year
        errors.add attribute, "Invalid year: #{date.year}"
      else
        result = date
      end
    end
    result
  end
end

app/controllers/adapt/application_controller.rb
# The base controller class from which all other controllers inherit.
#
# (c)2010 ANUSF

class Adapt::ApplicationController < ActionController::Base
  User = Adapt::User

  unless Rails.application.config.consider_all_requests_local
    rescue_from Exception,                            :with => :render_error
    rescue_from ActiveRecord::RecordNotFound,         :with => :render_not_found
    rescue_from ActionController::RoutingError,       :with => :render_not_found
    rescue_from ActionController::UnknownController,  :with => :render_not_found
    rescue_from ActionController::UnknownAction,      :with => :render_not_found
  end

  # -- the standard layout
  layout ADAPT::CONFIG['adapt.layout'] || 'application'

  # -- makes all helpers available in controllers
  helper :all

  # -- makes these controller methods available in views
  helper_method :current_user, :in_demo_mode, :users_may_change_roles
 
  # -- forbids all access not explicitly granted ('verboten' plugin)
  forbid_everything

  # -- protects from CSRF attacks via an authenticity token
  protect_from_forgery

  # -- this handles session expiration, invalid IP addresses, etc.
  around_filter :validate_session

  
  private

  def render_not_found(exception)
    Rails.logger.error(exception)
    @exception = exception
    render :template => "adapt/errors/404.html.haml", :status => 404
  end

  def render_error(exception)
    Rails.logger.error(exception)
    @exception = exception
    render :template => "adapt/errors/500.html.haml", :status => 500
    unless Rails.env == 'development'
      UserMailer.deliver_error_notification(exception)
    end
  end

  # Returns the current date as a nicely formatted string
  def current_date
    Date.today.strftime("%d %B %Y")
  end

  # The logged in user for the current session, or nil if none.
  def current_user
    return @current_user if defined?(@current_user)
    @current_user = User.find_by_id(session[:user_id])
  end

  # Whether the application is being run in a special demo mode.
  def in_demo_mode
    Rails.env != 'production'
  end

  # Whether the application is being run locally on the user's machine
  def in_local_mode
    Rails.env == 'local' or ADAPT::CONFIG['adapt.is.local']
  end

  # Whether users may assume arbitrary roles.
  def users_may_change_roles
    in_demo_mode
  end

  # Whether to bypass OpenID verification.
  def bypass_openid
    %{development test cucumber}.include?(Rails.env) or in_local_mode
  end

  # Starts a new session in which the given user is logged in.
  def new_session(user = nil)
    reset_session
    session[:user_id] = user && user.id
    session[:ip] = request.remote_ip
  end

  # Forced logout for current user.
  def kill_session(message)
    redirect_to logout_url(:message => message + " Please log in again!")
  end

  def local_request?
    request.remote_ip == "127.0.0.1"
  end

  # This is called as an around filter for all controller actions and
  # handles session expiration, invalid IP addresses, etc.
  def validate_session
    if in_local_mode
      # -- local instances can not be accessed from other host
      if request.remote_ip != "127.0.0.1"
        flash.now[:error] = "Remote access denied."
        render :text => '', :layout => true
      end
    elsif current_user
      # -- if someone is logged in, check some things
      begin
        SessionInfo.current_user = current_user
        SessionInfo.request_host = request.host_with_port
        # -- terminate session if expired or the IP address has changed
        if request.remote_ip != session[:ip]
          kill_session "Your network connection seems to have changed."
        elsif !session[:expires_at] or session[:expires_at] < Time.now
          kill_session "Your session has expired."
        end
      rescue ActiveRecord::RecordNotFound
        # -- handle stale session cookies
        kill_session "You seem to have a stale session cookie."
      end
    end

    # -- call the controller action
    yield

    # -- make session expire after an hour of inactivity
    session[:expires_at] = 1.hour.since
  end
end

app/controllers/adapt/attachments_controller.rb
class Adapt::AttachmentsController < ApplicationController
  # ----------------------------------------------------------------------------
  # Authorization and other filtering.
  # ----------------------------------------------------------------------------

  # -- find referenced resources before performing authorization
  before_authorization_filter :find_attachment

  # -- declare access permissions via the 'verboten' plugin
  permit :download, :if => :may_view

  private

  # Finds the attachment with id specified in the request and the study it
  # belongs to.
  def find_attachment
    @attachment = Adapt::Attachment.find_by_id(params[:id])
    @study = @attachment.study if @attachment
  end

  # Whether the current user may view the referenced study.
  def may_view
    @study and @study.can_be_viewed_by current_user
  end

  # ----------------------------------------------------------------------------
  # Actions this controller provides.
  # ----------------------------------------------------------------------------
  public

  # This custom action provides a file download for the referenced attachment.
  def download
    send_file(@attachment.stored_path,
              :filename => @attachment.name,
              :disposition => "attachment",
              :stream => true,
              :buffer_size => 1024 * 1024)
  end
end

app/controllers/adapt/dois_controller.rb
require 'httparty'

class Adapt::DoisController < ApplicationController
  before_authorization_filter :find_doi, :except => [ :index, :new, :create ]

  permit(:index, :new, :create, :show, :edit, :update, :destroy,
         :if => :user_is_archivist)
  permit :transmit, :if => :user_is_archivist

  private

  def find_doi
    @doi = Adapt::Doi.find_by_id(params[:id])
  end

  def user_is_archivist
    current_user.is_archivist
  end

  public

  def index
  end

  def new
    @doi = Adapt::Doi.new :year => Time.now.year,
                          :publisher => "Australian Data Archive"
  end

  def create
    if params[:result] == "Cancel"
      flash[:notice] = 'DOI metadata creation cancelled.'
      redirect_to root_url
    else
      @doi = Adapt::Doi.new(params[:adapt_doi])

      if @doi.save
        flash[:notice] = 'DOI metadata created.'
        redirect_to adapt_doi_url(@doi)
      else
        flash.now[:error] =
          "DOI metadata creation failed. See fields marked in red."
        render :action => :new
      end
    end
  end

  def show
    respond_to do |format|
      format.html
      format.xml
    end
  end

  def edit
  end

  def update
    if params[:result] == "Cancel"
      flash[:notice] = 'DOI metadata edit cancelled.'
      redirect_to adapt_doi_url(@doi)
    elsif @doi.update_attributes(params[:adapt_doi])
      flash[:notice] = 'DOI metadata updated.'
      redirect_to adapt_doi_url(@doi)
    else
      flash.now[:error] =
        "DOI metadata creation failed. See fields marked in red."
      render :action => :new
    end
  end

  def destroy
  end

  # === Extra action for this resource

  def transmit
    if params[:result] == "Cancel"
      flash[:notice] = 'DOI creation cancelled.'
      redirect_to root_url
    elsif params[:result] == "Edit"
      redirect_to edit_adapt_doi_url(@doi)
    else
      xml = @doi.data_cite
      app_id = "00000000" # TODO read real app_id from secrets.rb
      ada_url = "http://ada.edu.au/ada/#{@doi.ddi_id}"
      service_url = "https://services.ands.org.au/doi/1.1/mint.json/"

      response = HTTParty.post(service_url,
                               :query => { :app_id => app_id, :url => ada_url },
                               :body => { :xml => "#{xml}" },
                               :limit => 10)
      Rails.logger.warn response
      # TODO analyse the response here, store new DOI or report error

      redirect_to adapt_doi_url(@doi)
    end
  end
end

app/controllers/adapt/licences_controller.rb
class Adapt::LicencesController < ApplicationController
  # ----------------------------------------------------------------------------
  # Authorization and other filtering.
  # ----------------------------------------------------------------------------

  # -- find referenced study before performing authorization
  before_authorization_filter :find_licence

  # -- declare access permissions via the 'verboten' plugin
  #    (new and create are currently disabled and may be found obsolete)
  permit :show do @study and @study.can_be_viewed_by current_user end

  private

  # Finds the licence specified in the request and the study it belongs to.
  def find_licence
    @licence = Adapt::Licence.find_by_id(params[:id])
    @study = @licence.study if @licence
  end

  # ----------------------------------------------------------------------------
  # The standard actions this controller implements. All action code relies on
  # the @study variable having been set by a before filter.
  # ----------------------------------------------------------------------------
  public

  def show
    @text = @licence.text(false)
  end
end

app/helpers/adapt/application_helper.rb
# Methods added to this helper will be available to all templates in the
# application.
module Adapt::ApplicationHelper
  # Trims strings longer than the given size.
  def clip_text(text, size)
    if text.length > size then text[0, size-5] + "[...]" else text end
  end

  # Does normal html encoding plus replaces blank text with a default value.
  def cleanup(text, default = "&mdash;".html_safe)
    text.blank? ? default : h(text)
  end

  # Translates some formatting into HTML
  def format_text(text)
    #TODO This did not work with jruby, but should now in production:
    #
    #     sanitize(RedCloth.new(text).to_html)

    chunks = text.split("\n").reject(&:blank?)
    sanitize(chunks.map { |p| "<p>#{p}</p>" }.join("\n"))
  end
end

app/helpers/adapt/attachments_helper.rb
module Adapt::AttachmentsHelper
  def format_attachment(attachment)
    extra =
      link_to(h(attachment.name), download_adapt_attachment_path(attachment)) +
      (attachment.restricted? ? ' <em>(restricted)</em>'.html_safe : '')
    t = if attachment.description.blank?
          "<p>#{extra} &mdash;  <em>(no description)</em></p>"
        else
          format_text(attachment.description).sub(/<p>/, "<p>#{extra} &mdash; ")
        end
    t.html_safe
  end
end

app/helpers/adapt/layout_helper.rb
# These helper methods can be called in templates to set variables to be used in
# the layout.
module Adapt::LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args.map(&:to_s)) }
  end
  
  def javascript(*args)
    args = args.map { |arg| arg == :defaults ? arg : arg.to_s }
    content_for(:js) { javascript_include_tag(*args) }
  end
end

app/helpers/adapt/studies_helper.rb
module Adapt::StudiesHelper
  def date(date_string)
    begin Adapt::PartialDate.new(date_string) rescue nil end.to_s
  end

  def each(list, &block)
    (list.blank? ? [] : list).each &block
  end

  def access_text(study)
    if study.licence.nil? or study.licence.access_mode.blank?
      nil
    else
      "#{study.licence.access_mode} (#{study.licence.access_phrase})"
    end
  end

  def tab_link(ref, text)
    the_class = (ref == @active_tab) ? "active-tab" : ""
    "<li class='tab-entry'>
       <a href='#{ref}' class='#{the_class}'>
         <span>#{text}</span>
       </a>
     </li>".html_safe
  end

  # Preserves paragraph breaks in Nesstar Publisher
  def format_for_Nesstar(text)
    chunks = sanitize(text).split("\n").reject(&:blank?)
    chunks.join("\n<![CDATA[\n]]><![CDATA[\n]]>\n").html_safe
  end

  # Takes care of formtastic markup for repeatable and/or composite attributes
  def tabular_fields(form, attr, options = {})
    obj = form.object
    title = I18n.t("formtastic.titles.#{attr}", :default => '')
    hint = I18n.t("formtastic.hints.#{obj.class.name.underscore}.#{attr}",
                  :default => '')
    outer_options = {
      :class => (obj.is_repeatable?(attr) ? 'repeatable ' : '') + 'with-table'
    }
    outer_options[:name] = title unless title.blank?
    outer_options[:name] = options[:name] if options.has_key?(:name)
    if obj.subfields(attr).blank?
      options[:label] = outer_options[:name] unless options.has_key? :label
      outer_options.delete(:name)
    end
    
    form.inputs outer_options do
      concat(content_tag('li') do
        concat(content_tag('table') do
          concat(table_header(form, attr, options))
          concat(content_tag('tbody') do
            concat(form.fields_for("#{attr}_items".to_sym) do |f|
              concat(content_tag('tr') do
                form.object.subfields_for_nesting(attr).each do |field|
                  as = get_option(options, field, :as) ||
                           form.send(:default_input_type, field)
                  concat(content_tag('td', :class => as) do
                    input_options = field_options(form, attr, field, options)
                    concat f.input(field, input_options)
                  end)
                end
              end)
            end)
          end)
        end)
        unless hint.blank?
          concat(content_tag('p', hint, :class => 'inline-hints'))
        end
        concat(content_tag('li', form.errors_on(attr)))
      end)
    end
  end

  def table_header(form, attr, options = {})
    content_tag('thead') do
      concat(content_tag('tr') do
        form.object.subfields_for_nesting(attr).each do |field|
          concat(content_tag('th') do |th|
            label = get_option(options, field, :label)
            required = get_option(options, field, :required)
            concat(form.label(label || field, :required => required))
          end)
        end
      end)
    end
  end

  def field_options(form, attr, field, options = {})
    result = { :label => false }
    as = get_option(options, field, :as)
    result[:as] = as unless as.nil?
    extra_html = (options[:html_for] || {})[field] || {}
    result[:input_html] = options[:input_html].merge extra_html
    if (options[:choices_on] || []).include? field
      result[:input_html][:'data-selection-id'] =
        "#adapt-#{form.object.subfields(attr) ? field : attr}-choices"
    end
    result
  end

  def get_option(options, field, key)
    if options.has_key? key
      val = options[key]
      val.is_a?(Hash) ? (val[field] if val.has_key?(field)) : val
    end
  end
end

app/views/adapt/studies/_approval_box.html.haml
.box
  = form_for @study, :url => approve_adapt_study_path(@study), |
                     :html => { :method => :post } do |f| |
    %label
      Archivist
      = f.select :archivist, @study.selections(:archivist)
    %hr
    %p
      Approve and assign to the selected archivist
      &nbsp;
      = f.submit :name => 'result', :value => 'Approve'
    %p
      or reopen for depositor to add further information
      &nbsp;
      = f.submit :name => 'result', :value => 'Reopen'
.clear

app/views/adapt/studies/_archivist_box.html.haml
.box
  = form_for @study, :url => manage_adapt_study_path(@study), |
                     :html => { :method => :post } do |f| |
    - if current_user.is_admin
      - role = 'an administrator'
    - else
      - 'the archivist for this study'
    == As #{role}, you can
    %ul
      - if @study.can_be_stored_by current_user
        - options = options_for_select(@study.selections(:id_range))
        %li
          = f.submit :name => 'result', :value => 'Store'
          the associated files under a study ID in the
          %label
            range
            = select_tag :id_range, options
        %li
          = f.submit :name => 'result', :value => 'Reopen'
          - if @study.owner == current_user
            for further editing within ADAPT.
          - else
            for the depositor to add further information.
      %li
        = f.submit :name => 'result', :value => 'Hand over'
        to the
        %label
          archivist
          = f.select :archivist, @study.selections(:archivist)
        %span.inline-hints
          A study can only be edited by its owner or assigned
          archivist. In order to allow another archivist to make changes or
          add data, you must first hand the study over to them. They in turn
          can keep the study, hand it back later or pass it on to yet
          another person.
.clear

app/views/adapt/studies/_attachment_fields.html.haml
- text = { :rows => 20, :cols => 30, :class => 'expandable' }
- tab_id = 'adapt-attachment-fields'

= @form.inputs 'Attached Files', :id => tab_id, :class => 'tab' do
  %h3 Files uploaded so far:
  %p= @form.errors_on(:attachments)
  - unless @study.attachments.empty?
    %p
      %em
        (Please select a category for each file and provide a short
        description where necessary. At least one data file is required.)

    %table
      %thead
        %tr
          %th Name
          %th Size
          %th Description
          %th Category
          %th Restricted?
          %th
            - if @study.attachments.any? { |a| a.name.ends_with?('.zip') }
              Extract
          %th Delete
      %tbody
        = @form.fields_for :attachments do |f|
          - attachment = f.object
          - categories = [['', '']] + attachment.selections(:category)
          %tr
            %td=link_to h(attachment.name), |
                  download_adapt_attachment_path(attachment) |
            %td=h number_to_human_size(attachment.size)
            %td.text= f.text_area :description, text
            %td
              = f.select :category, categories
              = f.errors_on :category
            %td.boolean= f.check_box :restricted
            %td.boolean
              - if attachment.name.ends_with?('.zip')
                = f.check_box :extract
            %td.boolean= f.check_box :_destroy

  = @form.inputs :class => 'inline' do
    %li.boolean
      = @form.check_box :update_from_manual
      = @form.label :update_from_manual, 'Update from manual uploads'
    %li
      %em== (Place files on #{@study.manual_upload_path_display}.)

  %h3 Select more files to upload:
  %p
    %em
      (You can upload files either separately or in batches packaged
      as ZIP files. The latter can be submitted as is or the
      individual files extracted after uploading.)
  = @form.semantic_fields_for :uploads, Adapt::Attachment.new do |f|
    - label = Rails.env.test? ? 'Upload' : false
    = f.input :content, :label => label, :as => :file, :required => false, |
                        :input_html => { :class => 'multi' } |

app/views/adapt/studies/_credit_fields.html.haml
- long = { :size => 35 }
- text = { :rows => 2, :cols => 25, :class => 'expandable' }
- tab_id = 'adapt-credit-fields'

= @form.inputs 'Credits and Acknowledgements', :id => tab_id, :class => 'tab' do
  = tabular_fields @form, :depositors, |
                  :input_html => long,
                  :required => { :name => true },
                  :choices_on => [:affiliation]
  = tabular_fields @form, :principal_investigators, |
                  :input_html => long,
                  :required => { :name => true },
                  :choices_on => [:affiliation]
  = tabular_fields @form, :data_producers, |
                  :input_html => long,
                  :required => false,
                  :choices_on => [:affiliation]
  = tabular_fields @form, :funding_agency, |
                  :input_html => long,
                  :required => false
  = tabular_fields @form, :other_acknowledgements, |
                  :input_html => { :size => 25 },
                  :required => false,
                  :choices_on => [:affiliation]
  = tabular_fields @form, :references, |
                  :as => :text,
                  :input_html => text,
                  :required => false

  = @form.inputs 'Affiliations', :class => 'adapt-choices', |
                                 :id => 'adapt-affiliation-choices' do
    %li.empty &nbsp
    - @study.selections(:affiliation).each do |entry|
      %li= entry

app/views/adapt/studies/_title_fields.html.haml
- tab_id = 'adapt-title-fields'

= @form.inputs 'Title and Abstract', :id => tab_id, :class => 'tab' do
  = @form.input :title, :input_html => { :cols => 60, :rows => 4 }, |
                        :required => true
  = @form.input :abstract, :input_html => { :cols => 60 }, :required => true

app/views/adapt/studies/edit.html.haml
- title "Edit Study"
- wait = ! @can_submit

%em
  %p
    Please supply as many details as possible. You can fill out this
    form in any order by simply moving between the tabs below. See the
    %a{ :href => '#adapt-edit-help', :class => 'tab-link' } Help
    tab for further tips and instructions.

= semantic_form_for @study, :url => adapt_study_path(@study), |
    :html => {:multipart => true} do |form| |
  - @form = form

  %div= submit_tag "Submit this study", :disabled => wait, :confirm => @warning
  %br

  .tab-container
    %ul.tab-index
      = tab_link('#adapt-title-fields', 'Title and Abstract')
      = tab_link('#adapt-data-fields', 'Data Description')
      = tab_link('#adapt-credit-fields', 'Credits')
      = tab_link('#adapt-attachment-fields', 'Attached Files')
      = tab_link('#adapt-licence-fields', 'Licence Details')
      = tab_link('#adapt-edit-help', 'Help')

    = render 'edit_help'
    = render 'title_fields'
    = render 'data_fields'
    = render 'credit_fields'
    = render 'attachment_fields'
    = render 'licence_fields'

  = form.buttons do
    - @button_texts.each do |value|
      = form.commit_button value, :button_html => { :name => 'result' }

app/views/adapt/studies/index.html.haml
- title "Deposits"

%table.zebra
  %thead
    %tr
      %th.noprint
      %th.noprint
      %th Title
      %th Created by
      %th Archivist
      %th Status
      %th Files
      %th ADA ID
  %tbody
    - for study in @studies
      %tr
        %td.noprint
          - if study.can_be_edited_by(current_user)
            = link_to "Edit", edit_adapt_study_path(study)
          - else
            = link_to "Summary", adapt_study_path(study)
        %td.noprint
          - if study.can_be_destroyed_by(current_user)
            = link_to "Delete", adapt_study_path(study), |
                      'data-confirm' => 'Really delete this study?', |
                      'data-method' => :delete |
        %td
          %p= clip_text h(study.title), 60
        %td=h study.owner.name
        %td=h study.archivist && study.archivist.name
        %td= study.status
        %td= study.attachments.count
        %td= study.identifier || "&mdash;".html_safe

app/views/adapt/studies/new.html.haml
- title "New Study"

= semantic_form_for @study, :url => adapt_studies_path do |f|
  = f.inputs do
    = f.input :title, :input_html => { :rows => 4, :cols => 80 }, |
      :required => true
    = f.input :abstract, :input_html => { :cols => 80 }, :required => true
  = f.buttons do
    - ['Save', 'Cancel'].each do |value|
      = f.commit_button value, :button_html => { :name => 'result' }

app/views/adapt/studies/show.html.haml
- title "Study Summary"

- if @study.can_be_approved_by current_user
  = render 'approval_box'
- if @study.can_be_managed_by current_user
  = render 'archivist_box'

- if @study.is_submitted
  %p
    %em
      Please be aware that the study details shown below refer to the
      study as it was first submitted and may not reflect all changes
      made on file at later stages.

%hr

.properties
  %ul
    %li
      %dfn Title:
      %em=h @study.title
    %li
      %dfn Abstract:
      =format_text @study.abstract
  %hr
  %ul
    %li
      %dfn Attachments:
      - if @study.attachments.empty?
        &mdash;
      - else
        %ul= render :partial => 'adapt/attachments/attachment', |
                    :collection => @study.attachments |
  %hr
  %ul
    %li
      %dfn Created by:
      =h @study.owner.name
    %li
      %dfn Access Mode:
      = cleanup access_text(@study)
    %li
      %dfn Status:
      =h @study.status
    %li
      %dfn ADA ID:
      = cleanup @study.identifier
    %li
      %dfn Archivist:
      = cleanup(@study.archivist && @study.archivist.name)

  %hr
  %ul
    %li
      %dfn Kind of data:
      - tmp = []
      - tmp << "qualitative" if @study.data_is_qualitative == '1'
      - tmp << "quantitative" if @study.data_is_quantitative == '1'
      - tmp = tmp.empty? ? [] : [tmp.join(" and ")]
      = cleanup((tmp + (@study.data_kind || [])).join(", ").humanize)
    %li
      %dfn Related data:
      = cleanup @study.data_relation
    %li
      %dfn Sample population:
      = cleanup @study.sample_population
    %li
      %dfn Time period:
      - range = [h(@study.period_start), h(@study.period_end)]
      = range.join(" &mdash; ").html_safe
    %li
      %dfn Response rate:
      = cleanup @study.response_rate
    %li
      %dfn Sampling procedure:
      = cleanup((@study.sampling_procedure || []).join(", ").humanize)
    %li
      %dfn Collection method:
      = cleanup((@study.collection_method || []).join(", ").humanize)
    %li
      %dfn Collection period:
      - range = [h(@study.collection_start), h(@study.collection_end)]
      = range.join(" &mdash; ").html_safe

  %hr
  %ul
    %li
      %dfn Depositor:
      - if @study.depositor_name.blank? and |
          @study.depositor_affiliation.blank? |
        &mdash;
      - else
        = "#{cleanup @study.depositor_name},"
        = cleanup @study.depositor_affiliation
    %li
      %dfn Principal Investigators:
      - if @study.principal_investigators.blank?
        &mdash;
      - else
        %ul
          - for item in @study.principal_investigators
            %li
              = "#{cleanup item["name"]},"
              = cleanup item["affiliation"]
    %li
      %dfn Data Producers:
      - if @study.data_producers.blank?
        &mdash;
      - else
        %ul
          - for item in @study.data_producers
            %li
              = "#{cleanup item["name"], "n.a."},"
              = cleanup item["affiliation"], "n.a."
    %li
      %dfn Funding:
      - if @study.funding_agency.blank?
        &mdash;
      - else
        %ul
          - for item in @study.funding_agency
            %li
              - data = []
              - data << item["agency"] unless item["agency"].blank?
              - unless item["grant_number"].blank?
                - data << "grant no. #{item["grant_number"]}"
              = cleanup data.join(", ")
    %li
      %dfn Acknowledgements:
      - if @study.other_acknowledgements.blank?
        &mdash;
      - else
        %ul
          - for item in @study.other_acknowledgements
            %li
              = "#{cleanup item["name"], "n.a."},"
              = cleanup item["affiliation"], "n.a."
              = "(#{cleanup item["role"], "n.a."})"
    %li
      %dfn References:
      - if @study.references.blank?
        &mdash;
      - else
        %ul
          - for item in @study.references
            %li
              %p= h item['citation']
              - unless item['link'].blank?
                %p= link_to h(item['link']), h(item['link'])
              = format_text item['description']
%hr
%p.links>
  = link_to "Show DDI", adapt_study_path(@study, :format => :xml)
  - if @study.can_be_edited_by current_user
    |
    = link_to "Edit", edit_adapt_study_path(@study)
    |
    = link_to "Delete", @study, :confirm => 'Really delete this study?', |
                                :method => :delete |

app/views/adapt/studies/show.xml.haml
= render 'adapt/studies/ddi.xml'