config/routes.rb
Adapt::Application.routes.draw do
  devise_for :users, :controllers => { :sessions => "sessions" } do
    get "login",  :to => "sessions#new"
    get "logout", :to => "sessions#destroy"
  end

  devise_scope :user do
    resources :sessions
  end

  namespace :adapt do
    resources :studies do
      member do
        post 'approve'
        post 'manage'
        post 'submit'
      end
    end

    resources :attachments do
      get 'download', :on => :member
    end

    resources :licences do
      post 'accept', :on => :member
    end

    resources :dois do
      post 'transmit', :on => :member
    end
  end

  root :to => 'adapt/studies#index'
end

app/helpers/adapt/layout_helper.rb
# These helper methods can be called in templates to set variables to be used in
# the layout.
module Adapt::LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args.map(&:to_s)) }
  end
  
  def javascript(*args)
    args = args.map { |arg| arg == :defaults ? arg : arg.to_s }
    content_for(:js) { javascript_include_tag(*args) }
  end
end

app/views/layouts/_body.html.haml
- flash.each do |type,msg|
  %div{ :class => "flash-#{type}" }= h(msg).gsub(/\n/, '<br/>')

%h1== ADAPT (#{Rails.env}) &mdash; #{yield :title}
  
#adapt= yield

app/views/layouts/_breadcrumbs.html.haml
%p
  %strong YOU ARE HERE:
  %a{ :href => request.path }
    = request.path
    = yield(:breadcrumbs)

app/views/layouts/_css_includes.html.haml
= stylesheet_link_tag 'application'

app/views/layouts/_includes.html.haml
= stylesheet_link_tag 'adapt-swell'

-#
  = javascript_include_tag 'jquery-1.4.2.min'
  = javascript_include_tag 'rails'

= javascript_include_tag 'jquery.tabs', 'jquery.tooltips', 'jquery.textarea-expander', 'jquery.choices', 'jquery.multifile', 'application', :cache => true
= yield(:head)

app/views/layouts/_js_includes.html.haml
= javascript_include_tag 'application'

app/views/layouts/_links.html.haml
%ul
  %li
    %p ADAPT
  - if user_signed_in?
    %li= link_to "View deposits", adapt_studies_path
    %li= link_to "Add study", new_adapt_study_path
    - if current_user.is_archivist
      %li= link_to "Mint DOI", new_adapt_doi_path

app/views/layouts/_login.html.haml
- if current_user
  .logged_in
    %span== #{current_user.role}:
    = current_user.email
  .formtastic
    - profile_url = 'https://ada.edu.au/staff/home'
    = link_to "Log Out", destroy_user_session_path, :id => 'logout_button'
    = link_to "View Profile", profile_url, :id => 'profile_button'

  - if not @exception and users_may_change_roles
    = form_for current_user, |
    :url => session_path(current_user) do |f| |
      = hidden_field_tag 'last_url', url_for
      = f.select :role, User::ROLES
      = f.submit :name => 'result', :value => 'Change Role'
- else
  <h1>USER Log-in</h1>
  .formtastic
    = link_to "LOG IN", new_user_session_path, :id => 'enter_button'
    - registration_url = ADAPT::CONFIG['ada.registration.url']
    = link_to "Register", registration_url, :id => 'register_button'

app/views/layouts/ada.html.erb
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=US-ASCII">
<script type="text/javascript">var NREUMQ=[];NREUMQ.push(["mark","firstbyte",new Date().getTime()]);</script><meta charset="UTF-8">
<script type="text/javascript">var NREUMQ=[];NREUMQ.push(["mark","firstbyte",new Date().getTime()]);</script><title><%= yield :title %></title>
<link href="https://ada.edu.au/stylesheets/reset.css?1325561413" media="screen" rel="stylesheet" type="text/css">
<link href="https://ada.edu.au/stylesheets/common.css?1325561413" media="screen" rel="stylesheet" type="text/css">
<link href="https://ada.edu.au/stylesheets/structure.css?1325561413" media="screen" rel="stylesheet" type="text/css">
<link href="https://ada.edu.au/stylesheets/navigation.css?1325561413" media="screen" rel="stylesheet" type="text/css">
<link href="https://ada.edu.au/stylesheets/clearfix.css?1325561413" media="screen" rel="stylesheet" type="text/css">
<link href="https://ada.edu.au/stylesheets/formtastic.css?1325561413" media="screen" rel="stylesheet" type="text/css">
<link href="https://ada.edu.au/stylesheets/formtastic_changes.css?1325561413" media="screen" rel="stylesheet" type="text/css">
<link href="https://ada.edu.au/stylesheets/dropdown.css?1325561413" media="screen" rel="stylesheet" type="text/css">
<link href="https://ada.edu.au/stylesheets/colour.css?1325561413" media="screen" rel="stylesheet" type="text/css">
<link href="https://ada.edu.au/stylesheets/jquery-explr-1.3.min.css?1325561413" media="screen" rel="stylesheet" type="text/css">
<link href="https://ada.edu.au/stylesheets/jquery-ui-1.8.9.custom/jquery-ui-1.8.9.ada.css?1325561413" media="screen" rel="stylesheet" type="text/css">
<link href="https://ada.edu.au/stylesheets/theme.css?1325561413" media="screen" rel="stylesheet" type="text/css">
<script src="https://ada.edu.au/javascripts/modernizr-1.5.min.js?1325561413" type="text/javascript"></script><script src="https://ada.edu.au/javascripts/jquery.min.js?1325561413" type="text/javascript"></script><script src="https://ada.edu.au/javascripts/rails.js?1325561413" type="text/javascript"></script><script src="https://ada.edu.au/javascripts/jquery.effects.core.js?1325561413" type="text/javascript"></script><script src="https://ada.edu.au/javascripts/scripts.js?1325561413" type="text/javascript"></script><script src="https://ada.edu.au/javascripts/application.js?1325561413" type="text/javascript"></script><script src="https://ada.edu.au/javascripts/jquery-explr-1.3.min.js?1325561413" type="text/javascript"></script><script src="https://ada.edu.au/javascripts/jquery.multi-open-accordion-1.0.1-ada.js?1325561413" type="text/javascript"></script><meta name="keywords" content="">
<!-- Google analytics integration --><script type="text/javascript">var _gaq = _gaq || [];_gaq.push(['_setAccount', 'UA-25243708-1']);_gaq.push(['_setDomainName', '.ada.edu.au']);_gaq.push(['_trackPageview']);
 (function() {var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);})();
  </script><%= render "layouts/css_includes" %><%= csrf_meta_tag %></head>
<!--[if lt IE 7 ]> <body class="ie6 default"> <![endif]--><!--[if IE 7 ]>    <body class="ie7 default"> <![endif]--><!--[if IE 8 ]>    <body class="ie8 default"> <![endif]--><!--[if (gt IE 8)|!(IE)]><!--><body class="default"> <!--<![endif]-->


		<header><div class="login"><%= render "layouts/login" %></div>

			<div class="masthead"><a href="https://ada.edu.au/ada/home">Australian Data Archive</a></div>
	</header><nav class="mainnav clearfix"><ul>
<li> <a href="https://ada.edu.au/ada/home" class="current" title="Home">Home</a>
				</li>
				<li> <a href="https://ada.edu.au/ada/subarchives" class="" title="Subarchives">Subarchives</a>
						<ul>
<li> <a href="https://ada.edu.au/crime-and-justice/home" title="Crime &amp; Justice">Crime &amp; Justice</a> </li>
								<li> <a href="https://ada.edu.au/qualitative/home" title="Qualitative">Qualitative</a> </li>
								<li> <a href="https://ada.edu.au/international/home" title="International">International</a> </li>
								<li> <a href="https://ada.edu.au/social-science/home" title="Social Science">Social Science</a> </li>
								<li> <a href="https://ada.edu.au/longitudinal/home" title="Longitudinal">Longitudinal</a> </li>
								<li> <a href="https://ada.edu.au/historical/home" title="Historical">Historical</a> </li>
								<li> <a href="https://ada.edu.au/indigenous/home" title="Indigenous">Indigenous</a> </li>
						</ul>
</li>
				<li> <a href="https://ada.edu.au/ada/data-access" class="" title="Data Access">Data Access</a>
						<ul>
<li> <a href="https://users.ada.edu.au/users/new" title="Register for ADA">Register for ADA</a> </li>
								<li> <a href="https://ada.edu.au/ada/ada-undertaking-forms" title="ADA Undertaking Forms">ADA Undertaking Forms</a> </li>
								<li> <a href="https://ada.edu.au/ada/search-ada" title="Search ADA">Search ADA</a> </li>
								<li> <a href="https://ada.edu.au/ada/browse" title="Browse ADA Catalogue">Browse ADA Catalogue</a> </li>
								<li> <a href="https://ada.edu.au/ada/access-requests" title="Access Requests">Access Requests</a> </li>
								<li> <a href="https://ada.edu.au/ada/access-conditions" title="Access conditions">Access conditions</a> </li>
						</ul>
</li>
				<li> <a href="https://ada.edu.au/ada/data-deposit" class="" title="Data Deposit">Data Deposit</a>
						<ul>
<li> <a href="https://ada.edu.au/ada/setting-access-conditions" title="Setting access conditions">Setting access conditions</a> </li>
								<li> <a href="https://ada.edu.au/ada/deposit-forms" title="Deposit forms">Deposit forms</a> </li>
								<li> <a href="https://ada.edu.au/ada/how-to-deposit-data" title="How to deposit data">How to deposit data</a> </li>
								<li> <a href="https://ada.edu.au/ada/why-deposit-data-" title="Why Deposit Data?">Why Deposit Data?</a> </li>
								<li> <a href="https://ada.edu.au/ada/preferred-formats" title="Preferred formats">Preferred formats</a> </li>
						</ul>
</li>
				<li> <a href="https://ada.edu.au/ada/user-guides" class="" title="User Guides">User Guides</a>
				</li>
				<li> <a href="https://ada.edu.au/ada/ada-news" class="" title="ADA News">ADA News</a>
				</li>
				<li> <a href="https://ada.edu.au/ada/about" class="" title="About">About</a>
						<ul>
<li> <a href="https://ada.edu.au/ada/about" title="About ADA">About ADA</a> </li>
								<li> <a href="https://ada.edu.au/ada/contact-ada" title="Contact ADA">Contact ADA</a> </li>
						</ul>
</li>
     </ul>
<div class="searchContainer">
		    <form action="https://ada.edu.au/search" method="get" id="search-form" class="formtastic">
		      <label for="menusearch"></label>
		      <input type="text" name="term" id="search_term" value="Search this site"><input type="hidden" name="archive_id" id="archive_id" value="7"><input type="submit" alt="Go" value="go" id="search_button">
</form>
	    </div>	
  </nav><nav class="subnav"><%= render "layouts/links" %></nav><nav class="breadcrumbs"><%= render "layouts/breadcrumbs" %></nav><section class="content"><div class="notice"></div>
    <div class="alert"></div>

  	<!-- page partial start -->
		<section class="main"><article><%= render "layouts/body" %></article></section><!-- page partial end --></section><section class="partners"><div class="captions">
				<p>Funding Partners </p>
				<p>Collaboration Partners</p>
		  </div>
			
    <div class="logos">
				<img src="https://ada.edu.au/images/content/logo_arc.gif" alt="logo_arc" width="90" height="56" class="partnersFirst"><img src="https://ada.edu.au/images/content/logo_ncr.gif" alt="logo_nrc" width="109" height="56"><img src="https://ada.edu.au/images/content/logo_anu.gif" width="90" height="56" alt="Logo_anu"><img src="https://ada.edu.au/images/content/logo_uwa.gif" width="114" height="56" alt="logo_uwa"><img src="https://ada.edu.au/images/content/logo_uts.gif" width="110" height="56" alt="logo_uts"><img src="https://ada.edu.au/images/content/logo_um.gif" width="110" height="56" alt="logo_um"><img src="https://ada.edu.au/images/content/logo_uq.gif" width="110" height="56" alt="logo_uq">
</div>
		<footer class="footer_small"><p>General Enquiries: <a href="https://ada.edu.au/#">ada@anu.edu.au</a></p>
		  <p>Web Enquiries: <a href="https://ada.edu.au/mailto:webmaster.ada@anu.edu.au?Subject=Website+enquiry">webmaster.adae@anu.edu.au</a></p> 
		  <p> &#169; Australian Data Archive</p>
      <p><em>Deployed HEAD at 2012-01-03 02:31
</em></p>
    </footer></section><script type="text/javascript">if (!NREUMQ.f) NREUMQ.f=function() {
NREUMQ.push(["load",new Date().getTime()]);
var e=document.createElement("script");
e.type="text/javascript";e.async=true;e.src="https://d1ros97qkrwjf5.cloudfront.net/28/eum/rum-staging.js";
document.body.appendChild(e);
if(NREUMQ.a)NREUMQ.a();
};
if(window.onload!==NREUMQ.f){NREUMQ.a=window.onload;window.onload=NREUMQ.f;};
NREUMQ.push(["nrf2","beacon-1.newrelic.com","5b09f5d928",212937,"J1ZZRUENVFpWQhlJVgNcRB5ACldBbFJPZkQITFA=",0,111,new Date().getTime()])</script><script type="text/javascript">if (!NREUMQ.f) NREUMQ.f=function() {
NREUMQ.push(["load",new Date().getTime()]);
var e=document.createElement("script");
e.type="text/javascript";e.async=true;e.src="https://d1ros97qkrwjf5.cloudfront.net/28/eum/rum-staging.js";
document.body.appendChild(e);
if(NREUMQ.a)NREUMQ.a();
};
if(window.onload!==NREUMQ.f){NREUMQ.a=window.onload;window.onload=NREUMQ.f;};
NREUMQ.push(["nrf2","beacon-1.newrelic.com","5b09f5d928",212937,"J1ZZRUENVFpWQhlJVgNcRB5ACldBbFJPZkQITFA=",0,112,new Date().getTime()])</script>
</body>
<script type="text/javascript">
      $(document).ready(function(){
      
     });
    </script><%= render "layouts/js_includes" %></html>